extern const GeoLayout x_block_geo[];
extern Lights1 x_block_f3dlite_material_lights;
extern Lights1 x_block_f3dlite_material_001_lights;
extern u8 x_block_ttm_textures_01800_rgba16_ci8[];
extern u8 x_block_ttm_textures_01800_rgba16_pal_rgba16[];
extern u8 x_block_ttm_textures_0C000_rgba16_ci4[];
extern u8 x_block_ttm_textures_0C000_rgba16_pal_rgba16[];
extern Vtx x_block_X_Block_mesh_layer_1_vtx_0[32];
extern Gfx x_block_X_Block_mesh_layer_1_tri_0[];
extern Vtx x_block_X_Block_mesh_layer_1_vtx_1[35];
extern Gfx x_block_X_Block_mesh_layer_1_tri_1[];
extern Gfx mat_x_block_f3dlite_material[];
extern Gfx mat_revert_x_block_f3dlite_material[];
extern Gfx mat_x_block_f3dlite_material_001[];
extern Gfx mat_revert_x_block_f3dlite_material_001[];
extern Gfx x_block_X_Block_mesh_layer_1[];
