extern const GeoLayout broken_l_mid_geo[];
extern Lights1 broken_l_mid_f3dlite_material_lights;
extern Lights1 broken_l_mid_f3dlite_material_001_lights;
extern u8 broken_l_mid_ttm_textures_01800_rgba16_ci8[];
extern u8 broken_l_mid_ttm_textures_01800_rgba16_pal_rgba16[];
extern u8 broken_l_mid_ttm_textures_0C000_rgba16_ci4[];
extern u8 broken_l_mid_ttm_textures_0C000_rgba16_pal_rgba16[];
extern Vtx broken_l_mid_Broken_L_Mid_mesh_layer_1_vtx_0[8];
extern Gfx broken_l_mid_Broken_L_Mid_mesh_layer_1_tri_0[];
extern Vtx broken_l_mid_Broken_L_Mid_mesh_layer_1_vtx_1[8];
extern Gfx broken_l_mid_Broken_L_Mid_mesh_layer_1_tri_1[];
extern Gfx mat_broken_l_mid_f3dlite_material[];
extern Gfx mat_revert_broken_l_mid_f3dlite_material[];
extern Gfx mat_broken_l_mid_f3dlite_material_001[];
extern Gfx mat_revert_broken_l_mid_f3dlite_material_001[];
extern Gfx broken_l_mid_Broken_L_Mid_mesh_layer_1[];
